### ISSUE TITLE
How to configure kally-razor with expressjs?

### ISSUE THREAD

**Issue by crk4** [nufyoot/kally-razor#7]
Actually I want to override the default view engine of expressjs with kally-razor. 

I have tried something like this... but cant get it..

var razor = kallyrazor({
    root: __dirname + '/views/',
    layout: 'shared/layout.html'
});
app.engine('html', function (path, options, fn) {
    fn(null, razor.render(path, options));
});

**Comment by nufyoot** [comment]
Thanks for the feedback!  I'll need to have a look at adding a proper express pathway, but it looks like you only need to add one line of code:

`app.set('views', __dirname + '/views/');`

I added that and express seemed to pick up the views just fine.  But let me know if that doesn't work!
