### ISSUE TITLE
How to Configure Kally-razor with expressjs?

### ISSUE THREAD

**Issue by crk4** [nufyoot/kally-razor#8]
Actually i want to override the default view engine for expressjs with kally-razor.

so that i can call like this,

export.index=function(req,res){
     res.render('index.html);
}

I have tried something like this... but cant get it..

var razor = kallyrazor({
    root: __dirname + '/views/',
    layout: 'shared/layout.html'
});
app.engine('html', function (path, options, fn) {
    fn(null, razor.render(path, options));
});

guide me !!

**Comment by nufyoot** [comment]
Have a look at Issue #7 and let me know if you still have questions!
